### ISSUE TITLE
Typescript Dashboard

### ISSUE THREAD

**Issue by bachmanntobias** [Slessi/slessi.github.io#1]
Hi, since I couldnt find another way to reach you, I try it this way. I am really interested in a project you mentioned there (https://github.com/creativetimofficial/material-dashboard-react/issues/5) is it possible that we can talk about it or you could provide your sourcecode. 
you can reach me: 
Email: t.bachmann@taponia.de
Phone: +49 6026 94 98 076
Thank you for your efforts.

**Comment by Slessi** [comment]
Removed repo by mistake, put it back up for u
https://github.com/Slessi/material-dashboard-react-ts
